-- Align public.partners primary key to `id` while keeping bookings.partner_id -> partners(slug).
-- Runs atomically inside the Supabase migration transaction (do not nest BEGIN/COMMIT).

-- 1) FK cleanup
alter table public.bookings drop constraint if exists bookings_partner_id_fkey;

-- 2) PK swap prep: ensure `id` exists, is NOT NULL, then attach GENERATED BY DEFAULT AS IDENTITY if missing
alter table public.partners add column if not exists id bigint;

do $backfill_id$
declare
  has_identity boolean;
begin
  select exists (
    select 1
    from pg_attribute a
    join pg_class c on a.attrelid = c.oid
    join pg_namespace n on c.relnamespace = n.oid
    where n.nspname = 'public'
      and c.relname = 'partners'
      and a.attname = 'id'
      and not a.attisdropped
      and coalesce(a.attidentity, '') <> ''
  )
  into has_identity;

  if not coalesce(has_identity, false) then
    update public.partners p
    set id = s.new_id
    from (
      select
        ctid,
        coalesce((select max(id) from public.partners), 0)
          + row_number() over (order by slug) as new_id
      from public.partners
      where id is null
    ) s
    where p.ctid = s.ctid;
  end if;
end $backfill_id$;

update public.partners
set id = default
where id is null;

alter table public.partners alter column id set not null;

do $ensure_identity$
declare
  has_identity boolean;
begin
  select exists (
    select 1
    from pg_attribute a
    join pg_class c on a.attrelid = c.oid
    join pg_namespace n on c.relnamespace = n.oid
    where n.nspname = 'public'
      and c.relname = 'partners'
      and a.attname = 'id'
      and not a.attisdropped
      and coalesce(a.attidentity, '') <> ''
  )
  into has_identity;

  if not coalesce(has_identity, false) then
    alter table public.partners alter column id add generated by default as identity;
  end if;
end $ensure_identity$;

do $sync_identity_seq$
declare
  seq text;
begin
  seq := pg_get_serial_sequence('public.partners', 'id');
  if seq is not null then
    perform setval(
      seq::regclass,
      (select coalesce(max(id), 1) from public.partners)
    );
  end if;
end $sync_identity_seq$;

-- 3) PK swap: drop slug PK, add id PK (idempotent if already on id)
do $pk_swap$
declare
  pk_cols text[];
begin
  select coalesce(
    array_agg(kcu.column_name order by kcu.ordinal_position),
    array[]::text[]
  )
  into pk_cols
  from information_schema.table_constraints tc
  join information_schema.key_column_usage kcu
    on tc.constraint_catalog = kcu.constraint_catalog
   and tc.constraint_schema = kcu.constraint_schema
   and tc.constraint_name = kcu.constraint_name
  where tc.table_schema = 'public'
    and tc.table_name = 'partners'
    and tc.constraint_type = 'PRIMARY KEY';

  if pk_cols = array['slug']::text[] then
    alter table public.partners drop constraint partners_pkey;
    alter table public.partners add primary key (id);
  elsif pk_cols = array['id']::text[] then
    null;
  elsif cardinality(pk_cols) = 0 then
    raise exception 'public.partners has no PRIMARY KEY; fix schema before re-running this migration';
  else
    raise exception 'public.partners has unexpected PRIMARY KEY columns: %', pk_cols;
  end if;
end $pk_swap$;

-- 4) Explicit UNIQUE constraint on slug (FK target), reusing index name from 20260419212000 when present
alter table public.partners drop constraint if exists partners_slug_key;

create unique index if not exists partners_slug_uidx on public.partners (slug);

alter table public.partners
  add constraint partners_slug_key unique using index partners_slug_uidx;

-- 5) FK restore when legacy `public.bookings` has `partner_id` (slug → partners.slug)
do $bookings_partner_fk$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'bookings'
      and column_name = 'partner_id'
  ) then
    alter table public.bookings drop constraint if exists bookings_partner_id_fkey;
    alter table public.bookings
      add constraint bookings_partner_id_fkey
      foreign key (partner_id) references public.partners (slug) on delete set null;
  end if;
end $bookings_partner_fk$;
