-- Partner registry for authentication + commissions (admin-managed).
-- Keeps compatibility with existing partner credit columns already used by the app.

create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  slug text not null,
  name text not null,
  token text not null,
  commission_percentage numeric(5,2) not null default 0 check (commission_percentage >= 0 and commission_percentage <= 100),
  is_active boolean not null default true,
  display_name text,
  partner_kind text not null default 'Partner',
  credit_limit numeric not null default 0 check (credit_limit >= 0),
  current_usage numeric not null default 0 check (current_usage >= 0),
  commission_rate numeric not null default 0 check (commission_rate >= 0 and commission_rate <= 100),
  pricing_model text not null default 'MARKUP' check (pricing_model in ('MARKUP', 'NET_PRICE')),
  total_commissions_earned numeric not null default 0 check (total_commissions_earned >= 0),
  updated_at timestamptz not null default now()
);

alter table public.partners add column if not exists id bigint generated by default as identity;
alter table public.partners add column if not exists name text;
alter table public.partners add column if not exists token text default '';
alter table public.partners add column if not exists commission_percentage numeric(5,2) default 0;
alter table public.partners add column if not exists is_active boolean default true;

update public.partners
set
  name = coalesce(nullif(name, ''), display_name, slug),
  token = coalesce(token, ''),
  commission_percentage = coalesce(commission_percentage, commission_rate, 0),
  display_name = coalesce(display_name, name, slug),
  updated_at = now()
where
  name is null
  or token is null
  or commission_percentage is null
  or display_name is null;

alter table public.partners alter column name set not null;
alter table public.partners alter column token set not null;
alter table public.partners alter column commission_percentage set not null;
alter table public.partners alter column is_active set not null;

create unique index if not exists partners_slug_uidx on public.partners (slug);
create index if not exists partners_active_idx on public.partners (is_active);
create index if not exists partners_name_idx on public.partners (name);

